### ISSUE TITLE
refactor: json_annotation

### ISSUE THREAD

**Issue by ethicnology** [ethicnology/dart-nostr#11]
@ryzizub proposed json_annotation in https://github.com/ethicnology/dart-nostr/issues/4 and https://github.com/ethicnology/dart-nostr/pull/10

This refactoring would reduce the code maintenance and solve some decoding issues.

During the code review of his PR, I noticed that some checks were removed, I tried to put them again, tests failed.
Since there are a lot of changes in this PR,I restarted from `develop` branch and introduced a minimalist change with json_annotation.

This is the commit to solve: https://github.com/ethicnology/dart-nostr/commit/aec073a609e266411815b021db2dd510bd4c72b3

Tests are failing on these two assert since the id produced by `getEventId()` does not match the provided (valid) id:
```dart
    assert(this.id == id);
    assert(bip340.verify(pubkey, id, sig));
```

I also notice that there will be an issue with `Event.from()` since `id` is generated by `getEventId()` which need a `late` initialization that seem not compatible with this json_annotation, see `LateInitializationError: Field 'id' has not been initialized.`

We need to find why json_annotation is introducing a side effect on the `getEventId()` function which makes generates wrongs id that triggers the assertions.

We also have to find how to deal with the `Event.from()` and `late id` since this function makes really handy to create and event without generating his `id` and `sig`

**Comment by ryzizub** [comment]
@ethicnology regarding to your issues im have updated the branch

1. There was breaking change that contructors where changed from positioned params to named params. I still thinks that positioned params are better, but to make this marge less breaking i changed it to positioned params for now

2. Regarding to failing events, i found that the tests were wrong.
Currently the asserts are not called in main branch in those two tests which failed in my branch. In my branch are asserts now called so its making it more bullet proof. Seems that the event pushed to code was also wrong, i tried 5 different events and all went ok. Maybe @ethicnology can you verify that event, i was not able to find it on my relays.

**Comment by ryzizub** [comment]
I updated my branch with the changes that im mentioning https://github.com/ethicnology/dart-nostr/pull/10/commits/73314d74d34169e9083bd21b7c418292bb9b755d

**Comment by ryzizub** [comment]
Changed events are here https://github.com/ethicnology/dart-nostr/pull/10/commits/73daaf5876d711d8b56abcab96c18fe9cbadb19d

**Comment by ryzizub** [comment]
This can be closed since its merged 🎉 Good job @ethicnology
