### ISSUE TITLE
 The function getPublicKey() does not pad the returned value with 0 if the calculated public key should have zeros at beginning

### ISSUE THREAD

**Issue by ethicnology** [ethicnology/dart-nostr#2]
https://github.com/nbd-wtf/dart-bip340/issues/4

**Comment by ethicnology** [comment]
https://github.com/ethicnology/dart-nostr/blob/main/lib/src/keychain.dart#L14

https://github.com/ethicnology/dart-nostr/blob/main/lib/src/keychain.dart#L39

**Comment by ryzizub** [comment]
Can be merged and closed https://github.com/ethicnology/dart-nostr/pull/20

**Comment by ethicnology** [comment]
@ryzizub merged in #20
