### ISSUE TITLE
How to read events?

### ISSUE THREAD

**Issue by Myzel394** [ethicnology/dart-nostr#22]
So I'm publishing a simple "hello world" event but there's no content given when reading the event.

```dart
socket = await WebSocket.connect(
  widget.relays[0],
);

socket.listen((rawEvent) async {
  final event = Message.deserialize(rawEvent);
  print(event); // event.message returns a 4-length array but without my content
});

socket.add(
  Event.from(kind: 4, tags: [], content: "Hello", privkey: _privateKey).serialize()
);
```

Does this library not support parsing contents?

**Comment by ethicnology** [comment]
1. You should read and try examples given in the documentation [here](https://pub.dev/packages/nostr/example) or in [example](https://github.com/ethicnology/dart-nostr/tree/develop/example) folder.
2. Usually I'm adding a delay before reading something to take in consideration the latency between client and relay (you can see it in examples).
3. You are using kind 4 which is reserved for [direct encrypted message](https://github.com/nostr-protocol/nips/blob/master/04.md)
4. Can you provide more information on what is the problem ? You saw rawEvent has not your content, which content, why it should be your content i can be any nostr message.

**Comment by Myzel394** [comment]
Hey @ethicnology, thanks for your answers.

The docs unfortunately do not document how to read the content of the events, they just print the event object itself.

Here's a minimal reproducible example:

```dart
final socket = await WebSocket.connect(url);

socket.listen((rawEvent) {
  // Print the PGP encrypted message here
  print(rawEvent);
})

final event = Event.from(
  kind: 0, // Can be any kind, I don't really care
  tags: [],
  content: message, // PGP encrypted message
  privKey: _privateKey,
)

socket.add(event.serialize());
```

I'm basically just trying to send a PGP encrypted message via Nostr and then read it later on.

I used kind 4 because it seems to be the one required for encrypted content.

**Comment by ethicnology** [comment]
`event.content` contain the content of the event
```dart
final event = Event.from(
  kind: 0, // Can be any kind, I don't really care
  tags: [],
  content: message, // PGP encrypted message
  privKey: _privateKey,
)
print(event.content);
```

**Comment by Myzel394** [comment]
@ethicnology I mean inside "socket.listen"

```dart
socket.listen((rawEvent) {

  // How do I read `content` here?
  print(rawEvent);
})
```

**Comment by ethicnology** [comment]
> I used kind 4 because it seems to be the one required for encrypted content.

This library do not support DirectEncryptedMessage, yet you can follow/contribute on this implementation here: https://github.com/ethicnology/dart-nostr/pull/23

So if you will have to cipher/decipher the content yourself for the moment.

If you use the kind=4 your message should follow the [nip4 specification](https://github.com/nostr-protocol/nips/blob/master/04.md)

Or your event will be not compatible with most of the clients

**Comment by Myzel394** [comment]
@ethicnology Since I'm encrypting this content using a different way than Nostr expects, I decided to use "kind: 1000". However, I can't read the content of it

**Comment by ethicnology** [comment]
> @ethicnology I mean inside "socket.listen"
> 
> ```dart
> socket.listen((rawEvent) {
> 
>   // How do I read `content` here?
>   print(rawEvent);
> })
> ```

First as i did in the documentation you should wait for the relay to answer by adding some delay https://github.com/ethicnology/dart-nostr/blob/develop/example/nostr_example.dart#L75

Then to deserialize any nostr message you can use [Message.deserialize()](https://github.com/ethicnology/dart-nostr/blob/develop/example/message_example.dart#L6) if the `Message.type` is equal to `EVENT` then `Message.message` will be an event, `var event = Message.message` to access the content you have to print `event.content`.

You can take a look in [dispute client](https://github.com/ethicnology/dispute/blob/develop/lib/widget/the_wall.dart#L85)

**Comment by Myzel394** [comment]
Okay it seems as if my event doesn't publish correctly, as I only get a `Message.type` of `OK` (even after adding a delay). Do you know why this is the case?

```dart
final socket = await WebSocket.connect(url);

final event = Event.from(
  kind: 0, // Can be any kind, I don't really care
  tags: [],
  content: message, // PGP encrypted message
  privKey: _privateKey,
)

socket.add(event.serialize());

await Future.delayed(Duration(seconds: 10));

socket.listen((rawEvent) {
  final event = Message.deserialize(rawEvent);

  print(event.type); // `OK`
})
```

**Comment by ethicnology** [comment]
This is how relays works, you send an event and he has to tell you if he stored your event in his database. 
A relay can reject an event for many reason, invalid, spamming etc…
see [NIP20](https://github.com/nostr-protocol/nips/blob/master/20.md)

**Comment by Myzel394** [comment]
Makes sense, but how do I read the event now so that I get an "EVENT" type?

**Comment by ethicnology** [comment]
Which event ?

You send an EVENT and the relay answer OK this is end of communication

**Comment by ethicnology** [comment]
If you want to receive events from a relay, you have to subscribe with a `REQ` message

Please read:
- [nostr nips](https://github.com/nostr-protocol/nips)
- [basics](https://github.com/nostr-protocol/nips/blob/master/01.md)

**Comment by Myzel394** [comment]
Ohhhhh okay I completely misunderstood how to read events. So after creating a `Request`, everything works now!
Sorry about that, this was totally my failure because I misunderstood the docs.

```dart
    final request = Request(generate64RandomHexChars(), [
      Filter(
        kinds: [1000],
        authors: [widget.nostrPublicKey],
        since: 1679242255,
      ),
    ]);

    socket = await WebSocket.connect(
      widget.relays[0],
    );

    socket.add(request.serialize());

    await Future.delayed(Duration(seconds: 1));

    socket.listen((rawEvent) async {
      print(rawEvent);
      final event = Message.deserialize(rawEvent);
      print(event.message);
    });
```
