### ISSUE TITLE
Get tags from event?

### ISSUE THREAD

**Issue by bigOconstant** [ethicnology/dart-nostr#32]
I'm trying to write something that needs to see the tags of a event. Is there a way to extract the tags out?

**Comment by ethicnology** [comment]
@bigOconstant 

You can access the tags of an event using the `tags` [attribute](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/event.dart#L38)

**Comment by bigOconstant** [comment]
> @bigOconstant
> 
> You can access the tags of an event using the `tags` [attribute](https://github.com/ethicnology/dart-nostr/blob/develop/lib/src/event.dart#L38)

In your readme [here](https://github.com/ethicnology/dart-nostr/blob/develop/README.md?plain=1#L184) you have 

```
 var event = Message.deserialize(eventPayload);
```

Which works when I scan for kind 1 like your example. But if I try to put that into a event with,

```
var event = Event.deserialize(event);
```

I get a crash,

```
uilt dartcommunitybot:dartcommunitybot.
Unhandled exception:
Exception: invalid input
#0      new Event.deserialize (package:nostr/src/event.dart:253:7)
```

**Comment by ethicnology** [comment]
Can you give the full code example of what you are trying to do ?

**Comment by bigOconstant** [comment]
Using a local test relay here but you can fill it in with any relay. I just need to understand how to get a message and get to the tag. What the order of things are. I see the tag in the raw output. This is taken from one your examples here. 

```dart
import 'dart:io';
import 'package:nostr/nostr.dart';

void main() async {
// Create a subscription message request with one or many filters
  Request requestWithFilter = Request(generate64RandomHexChars(), [
    Filter(
      kinds: [
        0,
        1,
      ],
      since: 0,
      limit: 100,
    )
  ]);

  // Connecting to a nostr relay using websocket
  WebSocket webSocket = await WebSocket.connect(
    'ws://192.168.1.75:2700', // Fill in with any relay
  );
  // if the current socket fail try another one
  // wss://nostr.sandwich.farm
  // wss://relay.damus.io

  // Send a request message to the WebSocket server
  webSocket.add(requestWithFilter.serialize());

  // Listen for events from the WebSocket server
  var count = 0;
  await Future.delayed(Duration(seconds: 10));
  webSocket.listen((event) {
    print('$event');
    var event2 = Event.deserialize(event);
    //event2.message.
    count = count + 1;
    print('Received events: $count');
    print(event2);
  });

  // Close the WebSocket connection
  await webSocket.close();
}
```

**Comment by ethicnology** [comment]
@bigOconstant 
> Which works when I scan for kind 1 like your example

It's probably not related with non kind 1 events since this library is supporting multiple kind of NIP listed on the README.

But we already encountered such problem with some events encoding, NOSTR is wide with heterogenous implementations.

You can try to print each payload to grab those which fail before deserializing

**Comment by bigOconstant** [comment]
Ok some of the de-serialize ok but some don't and it crashes. Sorry this is kinda me learning dart at the same time. Wonder if there is some kinda try catch structure here. I'll post a solution and then close it for others to read before i'm done.

**Comment by bigOconstant** [comment]
Ok so the outer layer is of type message,

```
message = Message.deserialize(event);
```

Then inside the message the field message is usually a event

```
Event yourevent = message.message;
```

And from there you can access the tags

```
print(yourevent.tags);
```

Thanks for help clarifying that. I guess i'll close this.
