### ISSUE TITLE
Adding request filters

### ISSUE THREAD

**Issue by ryzizub** [ethicnology/dart-nostr#4]
Thanks @ethicnology for this library ❤️ , would love to help you out as the number of flutter developers that is using nostr protocol is growing 🚀

First thing I don't see is request filter, i think having object can help for developing clients.
[In NIP-01](https://github.com/nostr-protocol/nips/blob/master/01.md)
It's pretty clear 

```
{
  "ids": <a list of event ids or prefixes>,
  "authors": <a list of pubkeys or prefixes, the pubkey of an event must be one of these>,
  "kinds": <a list of a kind numbers>,
  "#e": <a list of event ids that are referenced in an "e" tag>,
  "#p": <a list of pubkeys that are referenced in a "p" tag>,
  "since": <a timestamp, events must be newer than this to pass>,
  "until": <a timestamp, events must be older than this to pass>,
  "limit": <maximum number of events to be returned in the initial query>
}
```

I would love to add that and since the request filter is pretty simple, what about adding [json_serializable](https://pub.dev/packages/json_serializable) in this project?

**Comment by ethicnology** [comment]
@ryzizub Thanks for your return.

Following your request, I've implemented the request message with the ability to subscribe with multiple filters.

All the change are documented with examples and unit tests in the upcoming pull request #5 

Please give it a try and feel free to push a PR if a fix is needed or if you want to contribute to this library 
(the Close message is missing)
