### ISSUE TITLE
Inconsitency in events is breaking tags

### ISSUE THREAD

**Issue by ryzizub** [ethicnology/dart-nostr#8]
I found couple of nostr events have empty tags like 

`
"tags": [
          [
            "e",
            "68ae015bf4833a6ff0ed86564c5afaa65c31791d35e8432755535d02eafc4375"
          ],
          [
            "e",
            "de2d85a00a52ceb25f3cfc41e22d927f6166250f210f928e2552b97c0bd66dcf"
          ],
          [
            "p",
            "052acd328f1c1d48e86fff3e34ada4bfc60578116f4f68f296602530529656a2",
            ""
          ]
`

unfortunately thats breaking cast cause its making child another list

<img width="614" alt="Error" src="https://user-images.githubusercontent.com/32575328/214852756-d743f6a0-7088-4867-94fc-f76a4b132927.png">

I will send a PR to fix this, cause small inconsitency should not break this

**Comment by ryzizub** [comment]
this can be also fixed by #10

**Comment by ethicnology** [comment]
merged #9
